apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.providerClassName }}
  namespace: {{ .Values.namespace.name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.project.id }}/secrets/customer_name-{{ .Values.project.environment }}/versions/latest"
        path: "CUSTOMER_NAME"
      - resourceName: "projects/{{ .Values.project.id }}/secrets/metrics_user-{{ .Values.project.environment }}/versions/latest"
        path: "METRICS_USER"
      - resourceName: "projects/{{ .Values.project.id }}/secrets/metrics_password-{{ .Values.project.environment }}/versions/latest"
        path: "METRICS_PASSWORD"
  secretObjects:
    - secretName: {{ .Values.secrets.kubernetesSecretName }}
      type: Opaque
      data:
        - objectName: CUSTOMER_NAME
          key: CUSTOMER_NAME
        - objectName: METRICS_USER
          key: METRICS_USER
        - objectName: METRICS_PASSWORD
          key: METRICS_PASSWORD